---
title: "natlpower"
author: "Daniel Shapiro"
date: "12/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
```

```{r correlates}
correlates <- read_xlsx("raw-data/correlates_of_war.xlsx")

correlates <- correlates %>% 
  arrange(change) %>%
  mutate(ToHighlight = ifelse(Country == "Russia", "yes", "no" ))
```

```{r graph1}
corr <- ggplot(correlates, aes(x = reorder(Country, change), y = change, fill = ToHighlight)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country",
       y = "Percent Change in National Power",
       title = "Percent Change in National Power, 2018-2019, Correlates of War Formula") +
  scale_fill_manual(values = c("yes" = "red", "no" = "gray"), guide = FALSE ) +
  scale_y_continuous(labels = scales::percent)
corr

ggsave("corr.png")
```

```{r Chang}
chang <- read_xlsx("raw-data/chang.xlsx")

chang <- chang %>% 
  arrange(change) %>%
  mutate(ToHighlight = ifelse(Country == "Russia", "yes", "no" ))
```

```{r graph2}
cha <- ggplot(chang, aes(x = reorder(Country, change), y = change, fill = ToHighlight)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country",
       y = "Percent Change in National Power",
       title = "Percent Change in National Power, 2018-2019, Chin-Lung Chang Formula") +
  scale_fill_manual(values = c("yes" = "red", "no" = "gray"), guide = FALSE ) +
  scale_y_continuous(labels = scales::percent)
cha

ggsave("cha.png")
```

```{r EINP}
einp <- read_xlsx("raw-data/einp.xlsx")

einp <- einp %>%
  arrange(change) %>%
  mutate(ToHighlight = ifelse(Country == "Russia", "yes", "no" ))
```

```{r graph3}
ein <- ggplot(einp, aes(x = reorder(Country, change), y = change, fill = ToHighlight)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country",
       y = "Percent Change in National Power",
       title = "Percent Change in National Power, 2018-2019, EINP Formula") +
  scale_fill_manual(values = c("yes" = "green4", "no" = "gray"), guide = FALSE ) +
  scale_y_continuous(labels = scales::percent)
ein

ggsave("ein.png")
```

```{r GDPI}
gdpi <- read_xlsx("raw-data/gdpi.xlsx")

gdpi <- gdpi %>%
  arrange(change) %>%
  mutate(ToHighlight = ifelse(Country == "Russia", "yes", "no" ))
```

```{r graph4}
gdp <- ggplot(gdpi, aes(x = reorder(Country, change), y = change, fill = ToHighlight)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Country",
       y = "Change in GDP Compared to Global Average",
       title = "Percent Change in Gross Domestic Product Index (GDPI), 2018-2019",
       caption = "GDPI measures the ratio of a country's GDP to that of the world as a whole.") +
  scale_fill_manual(values = c("yes" = "red", "no" = "gray"), guide = FALSE ) +
  scale_y_continuous(labels = scales::percent)
gdp

ggsave("gdp.png")
```

